/****************************************************************************************
 * Tabela: SHOPEE_CONFIG
 * Descrição:
 *   Armazena as configurações de integração da Shopee para cada loja.
 *   Inclui tokens de acesso, URL de redirecionamento e flags de controle, como
 *   habilitação do boost automático.
 *
 * Colunas:
 *   ID            - NUMBER, NOT NULL, GENERATED BY DEFAULT AS IDENTITY
 *                   Identificador único do registro, gerado automaticamente.
 *
 *   SHOP_ID       - NUMBER, NULL
 *                   Identificador da loja associada a estas configurações.
 *
 *   ACCESS_TOKEN  - VARCHAR2(500), NULL
 *                   Token de acesso OAuth da Shopee para chamadas autenticadas.
 *
 *   REFRESH_TOKEN - VARCHAR2(500), NULL
 *                   Token usado para renovar o ACCESS_TOKEN quando expirar.
 *
 *   TOKEN_EXPIRA_EM - DATE, NULL
 *                   Data e hora de expiração do ACCESS_TOKEN.
 *
 *   REDIRECT_URL  - VARCHAR2(500), NULL
 *                   URL de redirecionamento usada no fluxo OAuth.
 *
 *   BOOST_ENABLED - CHAR(1), DEFAULT 'Y', CHECK (BOOST_ENABLED IN ('Y','N'))
 *                   Indica se o boost automático está habilitado ('Y') ou desabilitado ('N').
 *
 * Chaves e restrições:
 *   PRIMARY KEY (ID)
 *      - Garante unicidade de cada registro na tabela.
 *
 * Observações:
 *   - Cada loja pode ter uma linha de configuração.  
 *   - Tokens devem ser mantidos seguros e nunca expostos em logs ou repositórios públicos.
 *
 * Exemplo de uso:
 *   -- Verificar se o boost está habilitado para uma loja
 *   SELECT BOOST_ENABLED, ACCESS_TOKEN, REFRESH_TOKEN
 *   FROM SHOPEE_CONFIG
 *   WHERE SHOP_ID = 12345;
 ****************************************************************************************/


  CREATE TABLE "SHOPEE_CONFIG" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SHOP_ID" NUMBER, 
	"ACCESS_TOKEN" VARCHAR2(500), 
	"REFRESH_TOKEN" VARCHAR2(500), 
	"TOKEN_EXPIRA_EM" DATE, 
	"REDIRECT_URL" VARCHAR2(500), 
	"BOOST_ENABLED" CHAR(1) DEFAULT 'Y', 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CHECK (BOOST_ENABLED IN ('Y','N')) ENABLE
   ) ;

   COMMENT ON COLUMN "SHOPEE_CONFIG"."ID" IS 'Identificador único do registro. Gerado automaticamente pelo banco (IDENTITY).';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."SHOP_ID" IS 'Identificador da loja associada a estas configurações.';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."ACCESS_TOKEN" IS 'Token de acesso OAuth da Shopee para chamadas autenticadas.';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."REFRESH_TOKEN" IS 'Token usado para renovar o ACCESS_TOKEN quando expirar.';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."TOKEN_EXPIRA_EM" IS 'Data e hora de expiração do ACCESS_TOKEN.';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."REDIRECT_URL" IS 'URL de redirecionamento usada no fluxo OAuth.';
   COMMENT ON COLUMN "SHOPEE_CONFIG"."BOOST_ENABLED" IS 'Indica se o boost automático está habilitado (''Y'') ou desabilitado (''N'').';
   COMMENT ON TABLE "SHOPEE_CONFIG"  IS 'Armazena as configurações de integração da Shopee para cada loja, incluindo tokens OAuth e controle do boost automático.';